#!/bin/bash

export CC=i686-tachacoin-gcc
export LD=i686-tachacoin-ld
export CXX=i686-tachacoin-g++
export CPP=i686-tachacoin-cpp
export AR=i686-tachacoin-ar
export STRIP=i686-tachacoin-strip
export OBJCOPY=i686-tachacoin-objcopy

cd ${HOME}/bind

make "$@"