#!/bin/sh

set -e

case $TACHACOIN_NETWORK in
  local|regtest)
    SELECT_NETWORK=-regtest
    ;;
  test|testnet)
    SELECT_NETWORK=-testnet
    ;;
  main|mainnet)
    SELECT_NETWORK=
    ;;
  *)
    echo "Unknown network: $TACHACOIN_NETWORK"
    exit 1
esac

mkdir -p $TACHACOIN_DATADIR

exec tachacoind ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:45551 -rpcallowip=172.17.0.0/16 \
  -datadir=$TACHACOIN_DATADIR \
  -logevents \
  -rpcuser=$TACHACOIN_RPC_USER -rpcpassword=$TACHACOIN_RPC_PASS \
  -printtoconsole
